Repository openSUSE/obs-service-tar_scm, pull requests merged in 2018-06, with the labels that each got.

#236 Remove clone_dir if clone fails
  TarSCM/scm/git.py
Labels: bug, needs work

#239 add stub user docs in lieu of something proper (#238)
  README.md
Labels: documentation

#241 don't allow DEBUG_TAR_SCM to change behaviour (#240)
  TarSCM/cli.py
  TarSCM/config.py
  tests/testenv.py
  tests/unittestcases.py
Labels: enhancement
